version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mypy
    versions:
    - "0.812"
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: twine
    versions:
    - 3.4.1
  - dependency-name: tox
    versions:
    - 3.23.0
