name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
      max-parallel: 1

    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox and any other dependencies for test
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Run nox
        run: |
          python -V
          nox -s test-${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['ruff', 'isort', 'bandit', 'mypy', 'readme']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tox and any other dependencies for test
        run: |
          python -m pip install --upgrade pip
          pip install nox

      - name: Run nox
        run: nox -s ${{ matrix.env }}
